[package]
name = "mosquitto-mqtt"
version = "1.0.2"
authors = ["Aliev Yamanee <aliev.yamanee@gmail.com>"]
edition = "2018"

[dependencies]
mosquitto-mqtt-sys-rust = { git = "https://github.com/alievy/mosquitto-mqtt-sys-rust.git", branch = "main" }
log = "0.4.*"